### ISSUE TITLE
Simulator Error: Failed cast on undefined

### ISSUE THREAD

**Issue by microbit-sam** [Seeed-Studio/pxt-grove#9]
> micro:bit support reference: #22832

A customer has reported an error when they attempt to use the Grove MakeCode extension

```
pxtapp.js:24988 sim error: failed cast on undefined
   at init (pxt_modules/Grove/main.ts:220:9)
   at onGesture (pxt_modules/Grove/main.ts:79:5)
   at <main> (pxt_modules/Grove/main.ts:1:1)
```

The MakeCode code is as follows:
```
grove.onGesture(GroveGesture.Right, function () {
    basic.showString("R")
})
grove.onGesture(GroveGesture.Wave, function () {
    basic.showString("W")
})
grove.onGesture(GroveGesture.Up, function () {
    basic.showString("U")
})
grove.onGesture(GroveGesture.Down, function () {
    basic.showString("D")
})
grove.onGesture(GroveGesture.Left, function () {
    basic.showString("L")
})
grove.onGesture(GroveGesture.Anticlockwise, function () {
    basic.showString("A")
})
grove.onGesture(GroveGesture.Forward, function () {
    basic.showString("F")
})
grove.onGesture(GroveGesture.Backward, function () {
    basic.showString("B")
})
grove.onGesture(GroveGesture.Clockwise, function () {
    basic.showString("C")
})
basic.showIcon(IconNames.Yes)
basic.forever(function () {
	
})
```

**Comment by microbit-mark** [comment]
> micro:bit support reference: #23359

This repros just by adding the gesture block from the Grove extension. 

https://makecode.microbit.org/_M2c3mLUTAd70

**Comment by Pillar1989** [comment]
We have updated the relevant code. Please try again. If there is any problem, you can open the issue again
